### PR TITLE
Split up index.ios.js into separate files

### PR DESCRIPTION
**Pull request by sleroux**
Moved Browser to components/BrowserView to componentize it for inclusion in both iOS and Android apps. Moved AppRegistry/setup code to setup.js to add redux and other middleware in future patches. Fixed ReactDefaultsPrefs bug when running app from repo (https://github.com/facebook/react-native/issues/7719)

### CODE REVIEW

**Comment by thebnich** [comment]
Woot, thanks!

I'm having trouble getting this to run on Android, though. Getting the following error: `Requiring unknown module "./js/setup".` Any ideas? Current `master` does work on Android for me.

**Comment by sleroux** [comment]
Forgot to call the setup function in index.android.js. I think it should work now? I don't have the Android SDK installed yet.

**Comment by thebnich** [comment]
Hm, yeah I tried this already with no luck. Strange since `index.android.js` and `index.ios.js` are now identical. I'm not experienced enough with React Native to know whether this is actually a bug or just another finnickly deployment issue...

I'll play around to see if I can get it working.

**Comment by thebnich** [comment]
After restarting the React Packager, I started getting this error instead: `Application Browser has not been registered. This is either due to a require() error during initialization or failure to call AppRegistry.registerComponent.`

Changing `﻿﻿ReactBrowserV1` in `index.android.js` back to `Browser` fixes the problem, so it looks like it's a problem with the android project name being out-of-sync with the registered one.

@sleroux, how about we just revert the `ReactBrowserV1` -> `Browser` for now, so we can worry about a full rename in another PR?

**Comment by sleroux** [comment]
I've reverted the rename so now it's Browser. Looks like the mix up was in `MainActivity.java` where it defines the module name it looks for that is registered with `AppRegistry`. Changing that to `ReactBrowserV1` seemed to work but let's keep it `Browser` for now.

**Comment by thebnich** [comment]
😎

**Pull request merged**
